### ISSUE TITLE
JOIN query determinism bug

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#100]
In the UI test:

```
SELECT * FROM PRODUCTINTERPOLATED p, RATINGS1 r WHERE p.id = r.pid;
```

**Comment by okennedy** [comment]
```
mimir.algebra.MissingVariable: MIMIR_COL_DET_P_BRAND
	at mimir.algebra.ExpressionChecker.typeOf(Typechecker.scala:48)
	at mimir.algebra.Typechecker$$anonfun$schemaOf$1.apply(Typechecker.scala:110)
	at mimir.algebra.Typechecker$$anonfun$schemaOf$1.apply(Typechecker.scala:108)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at mimir.algebra.Typechecker$.schemaOf(Typechecker.scala:108)
	at mimir.algebra.Operator.schema(Operator.scala:49)
	at mimir.exec.Compiler.compile(Compiler.scala:82)
	at mimir.exec.Compiler.compile(Compiler.scala:28)
	at mimir.Database.query(Database.scala:88)
	at mimir.WebAPI.handleSelect(WebAPI.scala:98)
	at mimir.WebAPI.handleStatement(WebAPI.scala:62)
	at controllers.Application$$anonfun$query$1.apply(Application.scala:131)
	at controllers.Application$$anonfun$query$1.apply(Application.scala:126)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407)
	at play.api.mvc.Action$.invokeBlock(Action.scala:533)
	at play.api.mvc.Action$.invokeBlock(Action.scala:530)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.NoSuchElementException: key not found: MIMIR_COL_DET_P_BRAND
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:58)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:58)
	at mimir.algebra.ExpressionChecker.typeOf(Typechecker.scala:49)
	... 43 more

```
