### ISSUE TITLE
Trouble uploading CSV files

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#25]
```
[error] - play.core.server.netty.PlayDefaultUpstreamHandler - Cannot invoke the action
java.sql.SQLException: near ".": syntax error
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:397) ~[sqlite-jdbc-3.8.7.jar:na]
	at org.sqlite.core.NativeDB._exec(Native Method) ~[sqlite-jdbc-3.8.7.jar:na]
	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:116) ~[sqlite-jdbc-3.8.7.jar:na]
	at mimir.sql.JDBCBackend.update(JDBCBackend.scala:48) ~[classes/:na]
	at mimir.Database.update(Database.scala:94) ~[classes/:na]
	at mimir.Database.handleLoadTable(Database.scala:291) ~[classes/:na]
	at mimir.WebAPI.configure(WebAPI.scala:50) ~[classes/:na]
	at controllers.Application$$anonfun$loadTable$1$$anonfun$apply$1.apply(Application.scala:123) ~[classes/:na]
	at controllers.Application$$anonfun$loadTable$1$$anonfun$apply$1.apply(Application.scala:117) ~[classes/:na]
```

This issue occurs when uploading the file https://github.com/UBOdin/mimir/blob/master/test/data/CPUSpeed.csv

![screen shot 2015-07-27 at 6 04 02 pm](https://cloud.githubusercontent.com/assets/3641553/8919062/7e8431da-348a-11e5-814b-67f333035fce.png)

**Comment by Legacy25** [comment]
This is because of spaces in column names and values. I was under the impression that Mimir was not designed to support unquoted string values. I have fixed the upload problem by just quoting the values before passing it to the backend, and the table shows up fine from the sqlite3 terminal, but a basic ```SELECT * FROM CPUSpeed;``` fails from mimir. This is because the RAToSql class does not have support for columns with spaces in the aliases.

What would be the cleanest way to go about doing this?

**Comment by Legacy25** [comment]
Closing this.
