### ISSUE TITLE
Error when querying missing value lens

### ISSUE THREAD

**Issue by NickCellino** [UBOdin/mimir#268]
I tried to create a missing value lens:
```
mimir> CREATE LENS MISSING_VALUE_R AS SELECT * FROM R WITH MISSING_VALUE('B');
```
which worked fine. Then I tried querying the lens like so:
```
mimir> SELECT * FROM MISSING_VALUE_R;
```
and that gave me:
```
An unknown error occurred...
java.util.NoSuchElementException: None.get
mimir> 	at scala.None$.get(Option.scala:313)
	at scala.None$.get(Option.scala:311)
	at mimir.lenses.BestGuessCache.cacheTableDefinition(BestGuessCache.scala:28)
	at mimir.lenses.BestGuessCache$$anonfun$4.apply(BestGuessCache.scala:66)
	at mimir.lenses.BestGuessCache$$anonfun$4.apply(BestGuessCache.scala:63)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at mimir.lenses.BestGuessCache.buildOuterJoins(BestGuessCache.scala:63)
	at mimir.lenses.BestGuessCache.rewriteToUseCache(BestGuessCache.scala:105)
	at mimir.exec.Compiler.bestGuessQuery(Compiler.scala:209)
	at mimir.exec.Compiler.compile(Compiler.scala:80)
	at mimir.exec.Compiler.compile(Compiler.scala:29)
	at mimir.Database.query(Database.scala:118)
	at mimir.Mimir$$anonfun$handleQuery$1.apply$mcV$sp(Mimir.scala:137)
	at mimir.Mimir$$anonfun$handleQuery$1.apply(Mimir.scala:136)
	at mimir.Mimir$$anonfun$handleQuery$1.apply(Mimir.scala:136)
	at mimir.util.TimeUtils$.monitor(TimeUtils.scala:19)
	at mimir.Mimir$.handleQuery(Mimir.scala:136)
	at mimir.Mimir$.handleSelect(Mimir.scala:131)
	at mimir.Mimir$.eventLoop(Mimir.scala:98)
	at mimir.Mimir$.main(Mimir.scala:80)
	at mimir.Mimir.main(Mimir.scala)
```
This was using the latest version of master. Platform is OSX if that matters.

**Comment by NickCellino** [comment]
For some reason this is only happening when I run it inside IntelliJ. Everything works as expected when I build the jar and run it on the command line.

**Comment by okennedy** [comment]
This looks like you are running an older version of the code, or possibly running without the SQLite-inline backend. Are you passing any command-line parameters?

-O

**Comment by NickCellino** [comment]
Yep, it looks like I was running outdated code. I had the latest version of master, but I had to open up the SBT Tool Window in IntelliJ and press 'Refresh SBT Project' and now it works.
