### ISSUE TITLE
Column not found (TupleBundle)

### ISSUE THREAD

**Issue by shivang94** [UBOdin/mimir#270]
On running the query: `select AVG(tax) from  lineitem_run_1 where returnflag = 'A' group by quantity having AVG(extendedprice)>70000;` (all of the columns are deterministic) in the ImputeTiming test case getting the error:
```
java.util.NoSuchElementException: key not found: LINEITEM_RUN_1_QUANTITY
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
	at mimir.sql.SqlToRA$$anonfun$20.apply(SqlToRA.scala:358)
	at mimir.sql.SqlToRA$$anonfun$20.apply(SqlToRA.scala:358)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mimir.sql.SqlToRA.convert(SqlToRA.scala:358)
	at mimir.sql.SqlToRA.convert(SqlToRA.scala:66)
	at mimir.sql.SqlToRA.convert(SqlToRA.scala:54)
	at mimir.sql.SqlToRA.convert(SqlToRA.scala:52)
	at mimir.Database.select(Database.scala:506)
	at mimir.Database.query(Database.scala:161)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30$$anonfun$17.apply(VLDB2017TimingTest.scala:251)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30$$anonfun$17.apply(VLDB2017TimingTest.scala:249)
	at mimir.test.TestTimer$class.time(TestTimer.scala:9)
	at mimir.timing.vldb2017.VLDB2017TimingTest.time(VLDB2017TimingTest.scala:18)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30.apply(VLDB2017TimingTest.scala:249)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30.apply(VLDB2017TimingTest.scala:247)
	at org.specs2.specification.AroundTimeout$$anon$1.result$lzycompute$1(ExamplesTimeout.scala:37)
	at org.specs2.specification.AroundTimeout$$anon$1.org$specs2$specification$AroundTimeout$class$$anon$$result$1(ExamplesTimeout.scala:37)
	at org.specs2.specification.AroundTimeout$$anon$1$$anonfun$2.apply(ExamplesTimeout.scala:38)
	at org.specs2.matcher.Expectable.value$lzycompute(Expectable.scala:20)
	at org.specs2.matcher.Expectable.value(Expectable.scala:20)
	at org.specs2.matcher.TerminationMatcher$$anonfun$apply$1.apply(TerminationMatchers.scala:34)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by okennedy** [comment]
A fix for this is now available in the FixHaving branch.  There's one issue with the test cases that I want to track down before submitting a pull request.  Specifically, the optimizer doesn't seem to be collapsing adjacent Project operators.  I'm not entirely sure why.  I'll look at it later on.

@mrb24  if you have a few cycles to spare before I do maybe you could have a look?
