### ISSUE TITLE
Error while printing results (TupleBundle)

### ISSUE THREAD

**Issue by shivang94** [UBOdin/mimir#271]
While trying to print results: 
```
db.query(queryString,tupleBundle) { results =>
                 time { results.foreach { row => println(row) } }
```
Getting the error:
```
java.lang.ArrayIndexOutOfBoundsException: -1
	at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:44)
	at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:48)
	at mimir.exec.result.LazyRow.apply(LazyRow.scala:16)
	at mimir.exec.result.SampleRow$$anonfun$values$1.apply(SampleResultIterator.scala:44)
	at mimir.exec.result.SampleRow$$anonfun$values$1.apply(SampleResultIterator.scala:44)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at mimir.exec.result.SampleRow.values(SampleResultIterator.scala:44)
	at mimir.exec.result.SampleRow.possibilities(SampleResultIterator.scala:68)
	at mimir.exec.result.SampleRow.apply(SampleResultIterator.scala:53)
	at mimir.exec.result.SampleRow$$anonfun$tuple$1.apply(SampleResultIterator.scala:47)
	at mimir.exec.result.SampleRow$$anonfun$tuple$1.apply(SampleResultIterator.scala:47)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mimir.exec.result.SampleRow.tuple(SampleResultIterator.scala:47)
	at mimir.exec.result.Row$class.toString(Row.scala:40)
	at mimir.exec.result.SampleRow.toString(SampleResultIterator.scala:36)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintStream.println(PrintStream.java:821)
	at scala.Console$.println(Console.scala:148)
	at scala.Predef$.println(Predef.scala:315)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30$$anonfun$17$$anonfun$18$$anonfun$apply$12$$anonfun$apply$mcV$sp$3.apply(VLDB2017TimingTest.scala:252)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30$$anonfun$17$$anonfun$18$$anonfun$apply$12$$anonfun$apply$mcV$sp$3.apply(VLDB2017TimingTest.scala:252)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at mimir.exec.result.SampleResultIterator.foreach(SampleResultIterator.scala:8)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30$$anonfun$17$$anonfun$18$$anonfun$apply$12.apply$mcV$sp(VLDB2017TimingTest.scala:252)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30$$anonfun$17$$anonfun$18$$anonfun$apply$12.apply(VLDB2017TimingTest.scala:252)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30$$anonfun$17$$anonfun$18$$anonfun$apply$12.apply(VLDB2017TimingTest.scala:252)
	at mimir.test.TestTimer$class.time(TestTimer.scala:9)
	at mimir.timing.vldb2017.VLDB2017TimingTest.time(VLDB2017TimingTest.scala:18)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30$$anonfun$17$$anonfun$18.apply(VLDB2017TimingTest.scala:252)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30$$anonfun$17$$anonfun$18.apply(VLDB2017TimingTest.scala:251)
	at mimir.Database.query(Database.scala:127)
	at mimir.Database.query(Database.scala:161)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30$$anonfun$17.apply(VLDB2017TimingTest.scala:251)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30$$anonfun$17.apply(VLDB2017TimingTest.scala:249)
	at mimir.test.TestTimer$class.time(TestTimer.scala:9)
	at mimir.timing.vldb2017.VLDB2017TimingTest.time(VLDB2017TimingTest.scala:18)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30.apply(VLDB2017TimingTest.scala:249)
	at mimir.timing.vldb2017.VLDB2017TimingTest$$anonfun$sampleFromLens$1$$anonfun$apply$30.apply(VLDB2017TimingTest.scala:247)
	at org.specs2.specification.AroundTimeout$$anon$1.result$lzycompute$1(ExamplesTimeout.scala:37)
	at org.specs2.specification.AroundTimeout$$anon$1.org$specs2$specification$AroundTimeout$class$$anon$$result$1(ExamplesTimeout.scala:37)
	at org.specs2.specification.AroundTimeout$$anon$1$$anonfun$2.apply(ExamplesTimeout.scala:38)
	at org.specs2.matcher.Expectable.value$lzycompute(Expectable.scala:20)
	at org.specs2.matcher.Expectable.value(Expectable.scala:20)
	at org.specs2.matcher.TerminationMatcher$$anonfun$apply$1.apply(TerminationMatchers.scala:34)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by okennedy** [comment]
This looks like it's pulling out an attribute that doesn't exist.  I'll have a look in a bit.
