### ISSUE TITLE
Analyze Broken

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#282]
On HEAD as of Dec 5

```
mimir> load 'test/r_test/r.csv';
...
mimir> create lens r_clean as select * from r with missing_value(column_1, column_2);
...
mimir> analyze select * from r_clean;
java.util.NoSuchElementException: key not found: MIMIR_ROWID
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at mimir.ctables.CTPercolator$$anonfun$30.apply(CTPercolator.scala:552)
	at mimir.ctables.CTPercolator$$anonfun$30.apply(CTPercolator.scala:552)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mimir.ctables.CTPercolator$.percolateLite(CTPercolator.scala:552)
	at mimir.ctables.CTPercolator$.percolateLite(CTPercolator.scala:154)
	at mimir.ctables.CTPercolator$.percolateLite(CTPercolator.scala:546)
	at mimir.ctables.CTPercolator$.percolateLite(CTPercolator.scala:517)
	at mimir.ctables.CTPercolator$.percolateLite(CTPercolator.scala:338)
	at mimir.ctables.CTPercolator$.percolateLite(CTPercolator.scala:154)
	at mimir.ctables.CTPercolator$.percolateLite(CTPercolator.scala:221)
	at mimir.ctables.CTPercolator$.percolateLite(CTPercolator.scala:221)
	at mimir.exec.mode.BestGuess$.rewriteRaw(BestGuess.scala:68)
	at mimir.exec.mode.BestGuess$.rewrite(BestGuess.scala:116)
	at mimir.exec.mode.CompileMode.apply(CompileMode.scala:36)
	at mimir.Database.query(Database.scala:125)
	at mimir.Database.query(Database.scala:168)
	at mimir.ctables.ReasonSet.size(ReasonSet.scala:20)
	at mimir.Mimir$$anonfun$handleAnalyze$1.apply(Mimir.scala:207)
	at mimir.Mimir$$anonfun$handleAnalyze$1.apply(Mimir.scala:206)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at mimir.Mimir$.handleAnalyze(Mimir.scala:206)
	at mimir.Mimir$.eventLoop(Mimir.scala:115)
	at mimir.Mimir$.main(Mimir.scala:94)
	at mimir.Mimir.main(Mimir.scala)
```

**Comment by mrb24** [comment]
fixed by commit f8b9299f6d60a60cdc6606c96372c1a2f6ee655d
