### ISSUE TITLE
More than two joins fail

### ISSUE THREAD

**Issue by Legacy25** [UBOdin/mimir#63]
ROWID problems.

Stack trace -

```
java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (ambiguous column name: __RHS_ROWID)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.throwex(DB.java:868)
	at org.sqlite.core.NativeDB.prepare(Native Method)
	at org.sqlite.core.DB.prepare(DB.java:211)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:81)
	at mimir.sql.JDBCBackend.execute(JDBCBackend.scala:32)
	at mimir.sql.Backend.execute(Backend.scala:12)
	at mimir.sql.Backend.execute(Backend.scala:17)
	at mimir.Database.query(Database.scala:87)
	at mimir.exec.Compiler.buildIterator(Compiler.scala:86)
	at mimir.exec.Compiler.buildIterator(Compiler.scala:66)
	at mimir.exec.Compiler.compile(Compiler.scala:35)
	at mimir.exec.Compiler.compile(Compiler.scala:25)
	at mimir.Database.query(Database.scala:127)
	at mimir.WebAPI.handleSelect(WebAPI.scala:107)
	at mimir.WebAPI.handleStatement(WebAPI.scala:76)
```

**Comment by okennedy** [comment]
Funky.  I'll have a look tonight.

-Oliver
-----
338H Davis Hall; (716) 645-1597; http://odin.cse.buffalo.edu/ <http://odin.cse.buffalo.edu/>

**Comment by okennedy** [comment]
What query does this happen on?

**Comment by Legacy25** [comment]
Seems to have been fixed somewhere down the line...weird, closing it...
