### ISSUE TITLE
Bug in construction of selection predicates

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#77]
This is `demo_ui.db` with type inference and schema matching lenses defined over ratings1.

![screen shot 2016-02-12 at 4 59 07 pm](https://cloud.githubusercontent.com/assets/3641553/13021604/1d5544ae-d1aa-11e5-8b6d-a23e21e8b436.png)

**Comment by okennedy** [comment]
```
java.sql.SQLException: Invalid schema: ROWID_MIMIR not in List((RATINGS1_PID,TString), (RATINGS1_RATING,TString), (RATINGS1_REVIEW_CT,TString))
	at mimir.exec.VarProjection$.compile(VarProjection.scala:43)
	at mimir.exec.VarProjection$$anonfun$compile$1.apply(VarProjection.scala:52)
	at mimir.exec.VarProjection$$anonfun$compile$1.apply(VarProjection.scala:52)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at mimir.exec.VarProjection$.compile(VarProjection.scala:52)
	at mimir.exec.VarProjection$$anonfun$compile$1.apply(VarProjection.scala:52)
	at mimir.exec.VarProjection$$anonfun$compile$1.apply(VarProjection.scala:52)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at mimir.exec.VarProjection$.compile(VarProjection.scala:52)
	at mimir.exec.ProjectionResultIterator$$anonfun$2.apply(ProjectionResultIterator.scala:34)
	at mimir.exec.ProjectionResultIterator$$anonfun$2.apply(ProjectionResultIterator.scala:29)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at mimir.exec.ProjectionResultIterator.<init>(ProjectionResultIterator.scala:29)
	at mimir.exec.Compiler.buildIterator(Compiler.scala:111)
	at mimir.exec.Compiler.compile(Compiler.scala:71)
	at mimir.exec.Compiler.compile(Compiler.scala:53)
	at mimir.Database.query(Database.scala:142)
	at mimir.WebAPI.handleSelect(WebAPI.scala:95)
```

```
PROJECT[PID <= CAST(RATINGS1_PID, {{ RATINGS1TYPED_0[] }}), RATING <= IF CAST(RATINGS1_RATING, {{ RATINGS1TYPED_1[] }}) IS NULL THEN {{ RATINGS1INTERPOLATED_1[ROWID_MIMIR] }} ELSE CAST(RATINGS1_RATING, {{ RATINGS1TYPED_1[] }}) END, REVIEW_CT <= CAST(RATINGS1_REVIEW_CT, {{ RATINGS1TYPED_2[] }})](
  SELECT[ ( (CAST(RATINGS1_RATING, {{ RATINGS1TYPED_1[] }}) IS NULL AND  ({{ RATINGS1INTERPOLATED_1[ROWID_MIMIR] }}<5) )  OR  (Not(CAST(RATINGS1_RATING, {{ RATINGS1TYPED_1[] }}) IS NULL) AND  (CAST(RATINGS1_RATING, {{ RATINGS1TYPED_1[] }})<5) ) ) ](
    RATINGS1(RATINGS1_PID:string, RATINGS1_RATING:string, RATINGS1_REVIEW_CT:string // ROWID_MIMIR:rowid)
  )
)
```
