### ISSUE TITLE
Explanations for JOINs

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#87]
Query on demo_final_state.db:
```
SELECT p.name, p.brand, r.rating FROM PRODUCT p, (SELECT * FROM RATINGS1INTERPOLATED UNION ALL SELECT * FROM RATINGS2MATCHED) r WHERE r.pid = p.id;
```

Exception:
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NoSuchElementException: key not found: ROWID_MIMIR]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:254) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.10-2.4.0.jar:2.4.0]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.10-2.4.0.jar:2.4.0]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.10-2.4.0.jar:2.4.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.10-2.4.0.jar:2.4.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.10-2.4.0.jar:2.4.0]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library-2.10.4.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library-2.10.4.jar:na]
	at scala.util.Try$.apply(Try.scala:161) [scala-library-2.10.4.jar:na]
	at scala.util.Failure.recover(Try.scala:185) [scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.10.4.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.10-2.4.0.jar:2.4.0]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.10-2.4.0.jar:2.4.0]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.10.4.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.10.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.10-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.10-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.10.4.jar:na]
Caused by: java.util.NoSuchElementException: key not found: ROWID_MIMIR
	at scala.collection.MapLike$class.default(MapLike.scala:228) ~[scala-library-2.10.4.jar:na]
	at scala.collection.AbstractMap.default(Map.scala:58) ~[scala-library-2.10.4.jar:na]
	at scala.collection.MapLike$class.apply(MapLike.scala:141) ~[scala-library-2.10.4.jar:na]
	at scala.collection.AbstractMap.apply(Map.scala:58) ~[scala-library-2.10.4.jar:na]
	at mimir.algebra.ExpressionChecker.typeOf(Typechecker.scala:41) ~[classes/:na]
	at mimir.algebra.ExpressionChecker.typeOf(Typechecker.scala:30) ~[classes/:na]
	at mimir.algebra.ExpressionChecker.assert(Typechecker.scala:12) ~[classes/:na]
	at mimir.algebra.Typechecker$.schemaOf(Typechecker.scala:95) ~[classes/:na]
	at mimir.algebra.Operator.schema(Operator.scala:11) ~[classes/:na]
	at mimir.exec.Compiler.buildDeterministicIterator(Compiler.scala:158) ~[classes/:na]
	at mimir.ctables.CTExplainer.provenanceQuery(CTExplainer.scala:277) ~[classes/:na]
	at mimir.ctables.CTExplainer.explainCell(CTExplainer.scala:132) ~[classes/:na]
	at mimir.Database.explainCell(Database.scala:241) ~[classes/:na]
	at mimir.WebAPI.getExplainObject(WebAPI.scala:186) ~[classes/:na]
	at controllers.Application$$anonfun$getExplainObject$1.apply(Application.scala:247) ~[classes/:na]
	at controllers.Application$$anonfun$getExplainObject$1.apply(Application.scala:240) ~[classes/:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:439) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:439) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[play_2.10-2.4.0.jar:2.4.0]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.10.4.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[play-iteratees_2.10-2.4.0.jar:2.4.0]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[play-iteratees_2.10-2.4.0.jar:2.4.0]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.10.4.jar:na]
	... 6 common frames omitted
```

**Comment by okennedy** [comment]
This should now be fully fixed in #92
